# Use the same base image version as the clams-python python library version
FROM ghcr.io/clamsproject/clams-python:$CLAMS_VERSION
# See https://github.com/orgs/clamsproject/packages?tab=packages&q=clams-python for more base images

################################################################################
# clams-python base images are based on debian distro
# install more system packages as needed using the apt manager
################################################################################

################################################################################
# main app installation
COPY ./ /app
WORKDIR /app
RUN pip3 install -r requirements.txt

# default command to run the CLAMS app in a production server 
CMD ["python3", "app.py", "--production"]
################################################################################
