name: "🗂 Add new issue to `apps` GHP"

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  call-assign:
    name: "🤙 Call GHP workflow"
    uses: clamsproject/.github/.github/workflows/repo-issue-project.yml@main
    secrets: inherit
    with:
      projectnum: 12

