name: test and send code coverage to codecov.io
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  test-and-codecov:
    - name: test and check coverage
      uses: clamsproject/.github/.github/workflows/sdk-codecov.yml@main
