name: build app-directory on documentation update

on:
  push:
    paths:
      "documentation/**.md"

permissions:
  contents: write
  pages: write
  id-token: write 

jobs:
    run-update:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

    build-directory:
      needs: run-update
      name: build app-directory
      uses: ./.github/workflows/update-documentation.yml
      with:
        branch-name: 'main'
      secrets: inherit
